export const brands = [
    "Korg",
    "Tijuana",
    "Don Correa",
    "Tiver",
    "Kemuel",
    "Jim Dunlop",
    "DAndrea",
    "Kirk Hammett",
    "Neon",
    "Kwc",
    "Daddario",
    "NUX",
    "CASIO",
    "Suant",
    "Acorn",
    "SX",
    "Cort",
    "Leonard",
    "TEXAS",
    "Zagert",
    "Orellano",
    "Washburn",
    "Fender",
    "Cort",
    "Ashland",
    "Korner",
    "Stradella",
    "Yirelly",
    "Yamaha",
    "Knight",
    "Lincoln",
    "Headrush",
    "Laney",
    "Hartke",
    "Thunder",
    "Evans",
    "Remo",
    "Meinl",
    "Stagg",
    "La Special",
    "Vic Firth",

]

export const categories = [
    "Afinadores",
    "Correas",
    "Fundas",
    "Púas",
    "Cables",
    "Teclados",
    "Instrumentos de Cuerda",
    "Instrumentos de Viento",
    "Amplificadores",
    "Baterías y Percusión",
]